name: Subreddit Scraper

on:
  workflow_dispatch:  # allows manual trigger
  schedule:
    - cron: '0 0 * * *'  # runs daily at midnight UTC

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Try to download existing database
      id: download_db
      continue-on-error: true
      uses: actions/download-artifact@v4
      with:
        name: subreddit-database
        path: .

    - name: Run the scraper
      run: python InactiveBot.py  # replace with your actual script filename

    - name: Upload updated database
      uses: actions/upload-artifact@v4
      with:
        name: subreddit-database
        path: subreddits.db
