name: Commit Branch Test

on:
  workflow_dispatch:

jobs:
  commit-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout main branch
      uses: actions/checkout@v3
      with:
        ref: main

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Run test script
      run: python InactiveBot.py

    - name: Clone scraper-storage branch
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git clone --depth=1 --single-branch --branch scraper-storage https://github.com/${{ github.repository }} storage-temp

    - name: Commit dummy file to scraper-storage
      run: |
        cp dummy.txt storage-temp/
        cd storage-temp
        git add dummy.txt
        git commit -m "Test: Dummy file commit to scraper-storage" || echo "Nothing to commit"
        git push origin scraper-storage
