name: Subreddit Scraper

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  # daily at midnight UTC

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code (main branch)
      uses: actions/checkout@v3
      with:
        fetch-depth: 1

    - name: Download database from scraper-storage branch
      run: |
        git clone --depth=1 --single-branch --branch scraper-storage https://github.com/${{ github.repository }} temp-db
        cp temp-db/subreddits.db subreddits.db || echo "No existing DB found. Starting fresh."

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Print last token info (optional debug)
      run: |
        if [ -f "subreddits.db" ]; then
          echo "Database exists. Checking last token..."
          python -c "import sqlite3; conn = sqlite3.connect('subreddits.db'); c = conn.cursor(); c.execute('SELECT name FROM subreddits ORDER BY id DESC LIMIT 1'); print('Last subreddit added:', c.fetchone()); conn.close()"
        else
          echo "No database found. Starting fresh."

    - name: Run the scraper
      run: python InactiveBot.py

    - name: Upload updated database back to scraper-storage branch
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git clone --depth=1 --single-branch --branch scraper-storage https://github.com/${{ github.repository }} storage-repo
        cp subreddits.db storage-repo/
        cd storage-repo
        git add subreddits.db
        git commit -m "Update database on $(date)"
        git push
