name: Subreddit Scraper

on:
  schedule:
    - cron: "0 12 * * *"  # Runs every day at 12 PM UTC (adjust as needed)
  workflow_dispatch:  # Allow manual trigger

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Download previous database (if exists)
        uses: actions/download-artifact@v4
        with:
          name: subreddit-database
          path: .

      - name: Run the script
        run: python your_script_name.py  # replace with your actual filename

      - name: Upload updated database
        uses: actions/upload-artifact@v4
        with:
          name: subreddit-database
          path: subreddits.db
