name: Subreddit Scraper

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Try to download existing database
      id: download_db
      continue-on-error: true
      uses: actions/download-artifact@v4
      with:
        name: subreddit-database
        path: .

    - name: Print last token info (Optional debug)
      run: |
        if [ -f "subreddits.db" ]; then
          echo "Database exists. Checking last token..."
          python -c "import sqlite3; conn = sqlite3.connect('subreddits.db'); c = conn.cursor(); c.execute('SELECT name FROM subreddits ORDER BY id DESC LIMIT 1'); print('Last subreddit added:', c.fetchone()); conn.close()"
        else
          echo "No database found. Starting fresh."
        fi

    - name: Run the scraper
      run: python InactiveBot.py

    - name: Upload updated database
      uses: actions/upload-artifact@v4
      with:
        name: subreddit-database
        path: subreddits.db
