name: Subreddit Scraper

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight UTC

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout main repo
      uses: actions/checkout@v3
      with:
        ref: main

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: pip install praw

    - name: Download database from scraper-storage branch
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git clone --depth=1 --single-branch --branch scraper-storage https://github.com/${{ github.repository }} storage-temp
        cp storage-temp/subreddits.db . || echo "No existing DB found, starting fresh"

    - name: Run scraper script
      run: python InactiveBot.py
      env:
        CLIENT_ID: ${{ secrets.CLIENT_ID }}
        CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
        USERNAME: ${{ secrets.USERNAME }}
        PASSWORD: ${{ secrets.PASSWORD }}
        USER_AGENT: "subreddit-scraper-script"

    - name: Commit updated DB during run if available
      if: always()
      run: |
        if [ -f "ready-to-commit.txt" ]; then
          echo "Found updated DB. Pushing to branch..."
          cp subreddits.db storage-temp/
          cd storage-temp
          git add subreddits.db
          git commit -m "✅ Test: 10 subreddits scraped and stored" || echo "Nothing to commit"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git push origin scraper-storage
          rm ../ready-to-commit.txt
        else
          echo "No updates to push."
