name: Subreddit Scraper

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight UTC

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout main repo
      uses: actions/checkout@v3
      with:
        ref: main

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Download database from scraper-storage branch
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git clone --depth=1 --single-branch --branch scraper-storage https://github.com/${{ github.repository }} storage-temp
        cp storage-temp/subreddits.db . || echo "No existing DB found, starting fresh"

    - name: Run scraper for 5 hours 45 minutes
      timeout-minutes: 345
      run: python InactiveBot.py

    - name: Commit updated DB during run if available
      if: always()
      run: |
        if [ -f "ready-to-commit.txt" ]; then
          echo "Found updated DB. Pushing to branch..."
          cp subreddits.db storage-temp/
          cd storage-temp
          git add subreddits.db
          git commit -m "Auto commit: Updated DB during run" || echo "Nothing to commit"
          git push origin scraper-storage
          rm ../ready-to-commit.txt
        else
          echo "No updates to push."
