name: Test Scraper Commit

on:
  workflow_dispatch:

jobs:
  test-scrape-and-commit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout main repo
      uses: actions/checkout@v3
      with:
        ref: main

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: pip install praw

    - name: Clone scraper-storage branch
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git clone --depth=1 --single-branch --branch scraper-storage https://github.com/${{ github.repository }} storage-temp
        cp storage-temp/subreddits.db . || echo "Creating fresh DB"

    - name: Run the test scraper
      env:
        REDDIT_CLIENT_ID: ${{ secrets.REDDIT_CLIENT_ID }}
        REDDIT_CLIENT_SECRET: ${{ secrets.REDDIT_CLIENT_SECRET }}
        REDDIT_USERNAME: ${{ secrets.REDDIT_USERNAME }}
        REDDIT_PASSWORD: ${{ secrets.REDDIT_PASSWORD }}
      run: python InactiveBot.py

    - name: Commit test database
      run: |
        cp subreddits.db storage-temp/
        cd storage-temp
        git add subreddits.db
        git commit -m "✅ Test: 10 subreddits scraped and stored"
        git push origin scraper-storage
